### ISSUE TITLE
View ShoppingCart error if no Country and/or State exists in Locations

### ISSUE THREAD

**Issue by lfurzewaddock** [OShop/OShop#1]
With no countries or states configured in Locations the error further below is logged upon viewing the ShoppingCart;

I created 1 country and 1 state for that country and set the single country as default. I'm not sure if setting it as the default was required to resolve the error.

2015-06-15 19:02:35,961 [7] Orchard.Exceptions.DefaultExceptionPolicy - Default - An unexpected exception was caught
System.NullReferenceException: Object reference not set to an instance of an object.
   at OShop.Services.ShoppingCartResolvers.LocationResolver.BuildCart(IShoppingCartService ShoppingCartService, ShoppingCart Cart) in d:\inetpub\vhosts\staging.www.co.uk\v1-8-1\src\Orchard.Web\Modules\OShop\Services\ShoppingCartResolvers\LocationResolver.cs:line 38
   at OShop.Services.ShoppingCartService.BuildCart() in d:\inetpub\vhosts\staging.www.co.uk\v1-8-1\src\Orchard.Web\Modules\OShop\Services\ShoppingCartService.cs:line 226
   at OShop.Controllers.ShoppingCartController.Index() in d:\inetpub\vhosts\staging.www.co.uk\v1-8-1\src\Orchard.Web\Modules\OShop\Controllers\ShoppingCartController.cs:line 43
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass48.<InvokeActionMethodFilterAsynchronouslyRecursive>b__41()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass48.<InvokeActionMethodFilterAsynchronouslyRecursive>b__41()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass48.<InvokeActionMethodFilterAsynchronouslyRecursive>b__41()

**Comment by TFleury** [comment]
Countries are mandatory when using Locations, but it should not crash.
