### ISSUE TITLE
Checkout validate order error/logs

### ISSUE THREAD

**Issue by lfurzewaddock** [OShop/OShop#5]
See/follow steps to recreate from Issue #4 

Then... **5) Click 'Validate' button**

_~/OShop/Checkout/ValidateOrder_

**ERRORS logged below**

2015-06-24 13:08:08,339 [11] Orchard.ContentManagement.DefaultContentManager - Default - ObjectDisposedException thrown from IContentHandler by OShop.Handlers.OrderShippingPartHandler
System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at lambda_method(Closure )
   at Orchard.Data.SessionLocator.EnsureSession(IsolationLevel level) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\SessionLocator.cs:line 98
   at Orchard.Data.SessionLocator.Demand() in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\SessionLocator.cs:line 46
   at Orchard.Data.SessionLocator.For(Type entityType) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\SessionLocator.cs:line 40
   at Orchard.Data.Repository`1.get_Session() in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\Repository.cs:line 27
   at Orchard.Data.Repository`1.Get(Int32 id) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\Repository.cs:line 88
   at Orchard.Data.Repository`1.Orchard.Data.IRepository<T>.Get(Int32 id) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\Repository.cs:line 57
   at OShop.Handlers.OrderShippingPartHandler.<>c__DisplayClass9.<>c__DisplayClassb.<.ctor>b__3(OrderAddressRecord shippingAddress) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard.Web\Modules\OShop\Handlers\OrderShippingPartHandler.cs:line 29
   at Orchard.ContentManagement.Utilities.LazyField`1.GetValue() in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\Utilities\LazyField.cs:line 24
   at Orchard.ContentManagement.Utilities.LazyField`1.get_Value() in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\Utilities\LazyField.cs:line 10
   at OShop.Models.OrderShippingPart.get_ShippingAddress() in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard.Web\Modules\OShop\Models\OrderShippingPart.cs:line 22
   at OShop.Handlers.OrderShippingPartHandler.<>c__DisplayClass9.<.ctor>b__4(CreateContentContext context, OrderShippingPart part) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard.Web\Modules\OShop\Handlers\OrderShippingPartHandler.cs:line 33
   at Orchard.ContentManagement.Handlers.ContentHandler.InlineStorageFilter`1.Created(CreateContentContext context, TPart instance) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\Handlers\ContentHandler.cs:line 152
   at Orchard.ContentManagement.Handlers.StorageFilterBase`1.Orchard.ContentManagement.Handlers.IContentStorageFilter.Created(CreateContentContext context) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\Handlers\StorageFilterBase.cs:line 51
   at Orchard.ContentManagement.Handlers.ContentHandler.Orchard.ContentManagement.Handlers.IContentHandler.Created(CreateContentContext context) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\Handlers\ContentHandler.cs:line 267
   at Orchard.ContentManagement.DefaultContentManager.<>c__DisplayClass60.<Create>b__5d(IContentHandler handler) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\DefaultContentManager.cs:line 552
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\InvokeExtensions.cs:line 17
2015-06-24 13:08:08,455 [11] Orchard.ContentManagement.DefaultContentManager - Default - GenericADOException thrown from IContentHandler by OShop.Handlers.OrderPartHandler
NHibernate.Exceptions.GenericADOException: could not insert: [OShop.Models.OrderAddressRecord][SQL: INSERT INTO OShop_OrderAddressRecord (Company, FirstName, LastName, Address1, Address2, Zipcode, City, Country_id, State_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?); select SCOPE_IDENTITY()] ---> System.Data.SqlClient.SqlException: Invalid column name 'Country_id'.
Invalid column name 'State_id'.
Statement(s) could not be prepared.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
   at NHibernate.Id.IdentityGenerator.InsertSelectDelegate.ExecuteAndExtract(IDbCommand insert, ISessionImplementor session)
   at NHibernate.Id.Insert.AbstractReturningDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   --- End of inner exception stack trace ---
   at NHibernate.Id.Insert.AbstractReturningDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Object obj, ISessionImplementor session)
   at NHibernate.Action.EntityIdentityInsertAction.Execute()
   at NHibernate.Engine.ActionQueue.Execute(IExecutable executable)
   at NHibernate.Event.Default.AbstractSaveEventListener.PerformSaveOrReplicate(Object entity, EntityKey key, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.FireSave(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.Save(Object obj)
   at Orchard.Data.Repository`1.Create(T entity) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\Repository.cs:line 97
   at Orchard.Data.Repository`1.Orchard.Data.IRepository<T>.Create(T entity) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\Repository.cs:line 37
   at OShop.Extensions.AddressExtensions.CreateOrUpdate(IRepository`1 repository, OrderAddressRecord record) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard.Web\Modules\OShop\Extensions\AddressExtensions.cs:line 28
   at OShop.Handlers.OrderPartHandler.<>c__DisplayClassf.<.ctor>b__8(CreateContentContext context, OrderPart part) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard.Web\Modules\OShop\Handlers\OrderPartHandler.cs:line 56
   at Orchard.ContentManagement.Handlers.ContentHandler.InlineStorageFilter`1.Created(CreateContentContext context, TPart instance) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\Handlers\ContentHandler.cs:line 152
   at Orchard.ContentManagement.Handlers.StorageFilterBase`1.Orchard.ContentManagement.Handlers.IContentStorageFilter.Created(CreateContentContext context) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\Handlers\StorageFilterBase.cs:line 51
   at Orchard.ContentManagement.Handlers.ContentHandler.Orchard.ContentManagement.Handlers.IContentHandler.Created(CreateContentContext context) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\Handlers\ContentHandler.cs:line 267
   at Orchard.ContentManagement.DefaultContentManager.<>c__DisplayClass60.<Create>b__5d(IContentHandler handler) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\ContentManagement\DefaultContentManager.cs:line 552
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\InvokeExtensions.cs:line 17
2015-06-24 13:08:08,469 [11] NHibernate.AssertionFailure - Default - An AssertionFailure occurred - this may indicate a bug in NHibernate or in your custom types.
NHibernate.AssertionFailure: null id in OShop.Models.OrderAddressRecord entry (don't flush the Session after an exception occurs)
2015-06-24 13:08:08,472 [11] Orchard.Exceptions.DefaultExceptionPolicy - Default - An unexpected exception was caught
NHibernate.AssertionFailure: null id in OShop.Models.OrderAddressRecord entry (don't flush the Session after an exception occurs)
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.CheckId(Object obj, IEntityPersister persister, Object id, EntityMode entityMode)
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.GetValues(Object entity, EntityEntry entry, EntityMode entityMode, Boolean mightBeDirty, ISessionImplementor session)
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.OnFlushEntity(FlushEntityEvent event)
   at NHibernate.Event.Default.AbstractFlushingEventListener.FlushEntities(FlushEvent event)
   at NHibernate.Event.Default.AbstractFlushingEventListener.FlushEverythingToExecutions(FlushEvent event)
   at NHibernate.Event.Default.DefaultAutoFlushEventListener.OnAutoFlush(AutoFlushEvent event)
   at NHibernate.Impl.SessionImpl.AutoFlushIfRequired(ISet`1 querySpaces)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
   at NHibernate.Impl.AbstractQueryImpl2.List()
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Orchard.Workflows.Services.WorkflowManager.TriggerEvent(String name, IContent target, Func`1 tokensContext)
   at Orchard.Events.DelegateHelper.<>c__DisplayClass31`4.<BuildAction>b__30(Object target, Object[] p) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Events\DelegateHelper.cs:line 128
   at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Events\DefaultOrchardEventBus.cs:line 81
   at Orchard.Events.DefaultOrchardEventBus.TryInvoke(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Events\DefaultOrchardEventBus.cs:line 67
   at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Events\DefaultOrchardEventBus.cs:line 53
2015-06-24 13:08:08,481 [11] NHibernate.AssertionFailure - Default - An AssertionFailure occurred - this may indicate a bug in NHibernate or in your custom types.
NHibernate.AssertionFailure: null id in OShop.Models.OrderAddressRecord entry (don't flush the Session after an exception occurs)
2015-06-24 13:08:08,484 [11] Orchard.Exceptions.DefaultExceptionPolicy - Default - An unexpected exception was caught
NHibernate.AssertionFailure: null id in OShop.Models.OrderAddressRecord entry (don't flush the Session after an exception occurs)
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.CheckId(Object obj, IEntityPersister persister, Object id, EntityMode entityMode)
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.GetValues(Object entity, EntityEntry entry, EntityMode entityMode, Boolean mightBeDirty, ISessionImplementor session)
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.OnFlushEntity(FlushEntityEvent event)
   at NHibernate.Event.Default.AbstractFlushingEventListener.FlushEntities(FlushEvent event)
   at NHibernate.Event.Default.AbstractFlushingEventListener.FlushEverythingToExecutions(FlushEvent event)
   at NHibernate.Event.Default.DefaultAutoFlushEventListener.OnAutoFlush(AutoFlushEvent event)
   at NHibernate.Impl.SessionImpl.AutoFlushIfRequired(ISet`1 querySpaces)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
   at NHibernate.Impl.AbstractQueryImpl2.List()
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Orchard.Utility.Extensions.ReadOnlyCollectionExtensions.ToReadOnlyCollection[T](IEnumerable`1 enumerable) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Utility\Extensions\ReadOnlyCollectionExtensions.cs:line 8
   at Orchard.Data.Repository`1.Orchard.Data.IRepository<T>.Fetch(Expression`1 predicate) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard\Data\Repository.cs:line 73
   at OShop.Services.ShoppingCartService.GetUserCartRecord(Int32 OwnerId) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard.Web\Modules\OShop\Services\ShoppingCartService.cs:line 81
   at OShop.Services.ShoppingCartService.GetCartRecord(Boolean CreateIfNull) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard.Web\Modules\OShop\Services\ShoppingCartService.cs:line 61
   at OShop.Services.ShoppingCartService.Empty() in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard.Web\Modules\OShop\Services\ShoppingCartService.cs:line 183
   at OShop.Controllers.CheckoutController.ValidateOrderPost(String Payment) in d:\inetpub\vhosts\Orchard-Dev\v1-9-0-Test\src\Orchard.Web\Modules\OShop\Controllers\CheckoutController.cs:line 137
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()

**Comment by TFleury** [comment]
Is there a valid country selected in your order address ?

**Comment by lfurzewaddock** [comment]
Test address in use;

Co. Name 5
FirstName5 LastName5
Adr line 1
Adr line 2
AdrCity5
Kent
Adr zip code 5
United Kingdom

**DB table OShop_CustomerPartRecord row contents**

| Id | ContentItemRecord_id | UserId | FirstName | LastName | Email | DefaultAddressId |
| --- | --- | --- | --- | --- | --- | --- |
| 15 | 15 | 2 | FName | LName | NULL | 0 |

**DB table OShop_CustomerAddressPartRecord row contents**

| Id | ContentItemRecord_id | CustomerId | AddressAlias | Company | FirstName | LastName | Address1 | Address2 | Zipcode | City | LocationsCountryId | LocationsStateId |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 33 | 22 | 15 | Adr alias 5 | Co. Name 5 | FirstName5 | LastName5 | Adr line 1 | Adr line 2 | Adr zip code 5 | AdrCity5 | 1 | 1 |

**DB table OShop_LocationsCountryRecord row contents**

| Id | Enabled | Name | IsoCode | AddressFormat | ShippingZoneRecord_Id |
| --- | --- | --- | --- | --- | --- |
| 1 | 1 | United Kingdom | GB | {OrderAddress.Company} {OrderAddress.FirstName}{OrderAddress.LastName} {OrderAddress.Address1} {OrderAddress.Address2} {OrderAddress.City} {OrderAddress.State} {OrderAddress.Zipcode} {OrderAddress.Country} | 1 |

**DB table OShop_LocationsStateRecord row contents**

| Id | Enabled | Name | IsoCode | LocationsCountryRecord_Id | ShippingZoneRecord_Id |
| --- | --- | --- | --- | --- | --- |
| 1 | 1 | Kent | GB-KEN | 1 | NULL |

**Comment by TFleury** [comment]
Found the issue, another mismatch in migrations.
You can fix your instance renaming columns "LocationsCountryRecord_Id" and "LocationsStateRecord_Id" with "Country_Id" and "State_Id" on "OrderAddressRecord" table.
